--  https://cloudinary.com/console/c-2955f4b647c83c97fee5c6c06965f6/media_library/folders/bd8c0a17e2890b4a4d81cdd2876ba3360d

DROP TABLE IF EXISTS v_users;

CREATE TABLE v_users
(
    id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                varchar(30) NOT NULL CHECK ( email LIKE ('%@%') ),
    password             varchar(50) NOT NULL,
    name                 varchar(30) CHECK ( LENGTH(name) > 3 ),
    age                  integer CHECK (age > 9),
    url_photo            varchar(255),
    last_visit_date_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_active            boolean DEFAULT false

);

-- изменить тип данных строки:
-- ALTER TABLE v_users ALTER COLUMN id SET DATA TYPE text;
-- ALTER TABLE v_users RENAME COLUMN urlPhoto TO url_photo;
-- делаем так, чтобы по-умолчанию выставлялись false и текущий timestamp полям:
ALTER TABLE v_users
    ALTER column is_active SET DEFAULT false,
    ALTER column last_visit_date_time SET DEFAULT CURRENT_TIMESTAMP;

-- ALTER TABLE v_users ALTER column is_active DROP DEFAULT;

INSERT INTO "v_users" VALUES(1, 'v@v', 'r', 'vlad', 25,
        'https://res.cloudinary.com/vladry/image/upload/v1628196607/avatars/Vlad_avatar_tjrcut.jpg'),
       (2, 'rvy@ukr.net', '123', 'Ryab', 35,
        'https://res.cloudinary.com/vladry/image/upload/v1628196607/avatars/Taras_avatar_hnldon.jpg'),
       (3, 'Andrey@gmail.com', 12, 'Andrey', 23,
        'https://res.cloudinary.com/vladry/image/upload/v1628196607/avatars/Andrey_avatar_bxcjny.jpg'),
       (4, 'Ilya@ukr.net', '3842', 'Ilyev', 19,
        'https://res.cloudinary.com/vladry/image/upload/v1628196848/avatars/Ilya_avatar_ecn4wr.jpg'),
       (5, 'Tanya@ukr.net', 'yas2', 'Tanya', 29,
        'https://res.cloudinary.com/vladry/image/upload/v1628868305/avatars/Tanya_mi0o0m.png'),
       (6, 'Lar@gmail.com', 'larq102', 'Larisa', 40,
        'https://res.cloudinary.com/vladry/image/upload/v1628868305/avatars/Ira_yvvlml.png');

-- набиваем БД тестовыми юзерами:
INSERT INTO "v_users" (email, password, name, age, url_photo)
VALUES ('v@v', 'r', 'vlad', 25,
        'https://res.cloudinary.com/vladry/image/upload/v1628196607/avatars/Vlad_avatar_tjrcut.jpg'),
       ('rvy@ukr.net', '123', 'Ryab', 35,
        'https://res.cloudinary.com/vladry/image/upload/v1628196607/avatars/Taras_avatar_hnldon.jpg'),
       ('Andrey@gmail.com', 12, 'Andrey', 23,
        'https://res.cloudinary.com/vladry/image/upload/v1628196607/avatars/Andrey_avatar_bxcjny.jpg'),
       ('Ilya@ukr.net', '3842', 'Ilyev', 19,
        'https://res.cloudinary.com/vladry/image/upload/v1628196848/avatars/Ilya_avatar_ecn4wr.jpg'),
       ('Tanya@ukr.net', 'yas2', 'Tanya', 29,
        'https://res.cloudinary.com/vladry/image/upload/v1628868305/avatars/Tanya_mi0o0m.png'),
       ('Lar@gmail.com', 'larq102', 'Larisa', 40,
        'https://res.cloudinary.com/vladry/image/upload/v1628868305/avatars/Ira_yvvlml.png');



TRUNCATE v_users CASCADE;

SELECT *
FROM information_schema.columns
WHERE table_name = 'v_users';

TRUNCATE v_users CASCADE;

SELECT * from v_users;

UPDATE v_users
SET email = 'v@r',
    password = 'r' WHERE id=16;

DELETE FROM v_users WHERE id = 15;
UPDATE v_users SET email = 'v@r', password = 'r' where id = 2;
